
INVALID_FONTS = [
"Bokor",
"Lao Muang Khong",
"Lao Sans Pro",
"MS Outlook",
"Catamaran Black",
"Dubai",
"HoloLens MDL2 Assets",
"Lao Muang Don",
"Oxanium Medium",
"Rounded Mplus 1c",
"Moul Pali",
"Noto Sans Tamil",
"Webdings",
"Armata",
"Koulen",
"Yinmar",
"Ponnala",
"Noto Sans Tamil",
"Chenla",
"Lohit Devanagari",
"Metal",
"MS Office Symbol",
"Cormorant Garamond Medium",
"Chiller",
"Give You Glory",
"Hind Vadodara Light",
"Libre Barcode 39 Extended",
"Myanmar Sans Pro",
"Scheherazade",
"Segoe MDL2 Assets",
"Siemreap",
"Taprom",
"Times New Roman TUR",
"Playfair Display SC Black",
"Poppins Thin",
"Raleway Dots",
"Raleway Thin",
"Segoe MDL2 Assets",
"Segoe MDL2 Assets",
"Spectral SC ExtraLight",
"Txt",
"Uchen",
"Yinmar",
"Almarai ExtraBold",
"Fasthand",
"Exo",
"Freckle Face",
"Montserrat Light",
"Inter",
"MS Reference Specialty",
"MS Outlook",
"Preah Vihear",
"Sitara",
"Barkerville Old Face",
"Bodoni MT"
"Bokor",
"Fasthand",
"HoloLens MDL2 Assests",
"Libre Barcode 39",
"Lohit Tamil",
"Marlett",
"MS outlook",
"MS office Symbol Semilight",
"MS office symbol regular",
"Ms office symbol extralight",
"Ms Reference speciality",
"Segoe MDL2 Assets",
"Siemreap",
"Sitara",
"Symbol",
"Wingdings",
"Metal",
"Ponnala",
"Webdings",
"Aguafina Script"]


def valid_font(filename):
    for name in INVALID_FONTS:
        if name.lower() in str(filename).lower():
            return False
    return True
